# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 10 Nov 2020 04:39:28 +0000
*               @ALL          1
*               @user         8
