<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: chifek
 * Date: Tue, 04 May 2021 11:29:55 +0300
 */

$conf['title'] = 'kn0wledge_l1brary';
$conf['lang'] = 'ru';
$conf['license'] = 'cc-by-sa';
$conf['youarehere'] = 1;
$conf['fullpath'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['htmlok'] = 1;
$conf['target']['extern'] = '_blank';
$conf['proxy']['user'] = 'chifek';
$conf['proxy']['pass'] = '<b>NDEzR2hqY25qcT0=';
