<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Tue, 10 Nov 2020 04:39:28 +0000
 */
$conf['title'] = 'kn0wledge_l1brary';
$conf['lang'] = 'ru';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
