# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 10 Nov 2020 04:39:28 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

chifek:$2y$10$rtcoaSPAbdp8ke89jWk77OAuSrBBKRDSD6nJ/.meNCFDTYis5wy9O:ruslan:chifek@gmail.com:admin,user
s.lopareva:$2y$10$Z4sbPLNu6rPJjvOUyMRG8eCGt8Rlv/ixz5Fy.6Fzf07ze1igQEG02:Svetlana:s.lopareva@qsoft.ru:user
a.manerova:$2y$10$0fzC2CDtvasAwdldSjc8te9GTM2RVbHZXaop8kypY4SVzW1weFP7a:Anna:a.manerova@qsoft.ru:user
