# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 10 Nov 2020 04:39:28 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

chifek:$2y$10$rtcoaSPAbdp8ke89jWk77OAuSrBBKRDSD6nJ/.meNCFDTYis5wy9O:ruslan:chifek@gmail.com:admin,user
